In [2]:
import os
os.environ["KERAS_BACKEND"] = "jax"
import keras

In [3]:
x = keras.ops.ones(shape=(2, 1))
x



Platform 'METAL' is experimental and not all JAX functionality may be correctly supported!


Metal device set to: Apple M3 Pro


W0000 00:00:1732561111.207968 35839590 mps_client.cc:510] WARNING: JAX Apple GPU support is experimental and not all JAX functionality is correctly supported!
I0000 00:00:1732561111.219700 35839590 service.cc:145] XLA service 0x60000378a000 initialized for platform METAL (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1732561111.219716 35839590 service.cc:153]   StreamExecutor device (0): Metal, <undefined>
I0000 00:00:1732561111.222024 35839590 mps_client.cc:406] Using Simple allocator.
I0000 00:00:1732561111.222031 35839590 mps_client.cc:384] XLA backend will use up to 28989243392 bytes on device 0 for SimpleAllocator.


Array([[1.],
       [1.]], dtype=float32)

In [4]:
x = keras.ops.zeros(shape=(2,1))

In [10]:
rand_x = keras.random.uniform(shape=(3,1))

rand_x

Array([[0.30910337],
       [0.25909734],
       [0.5616666 ]], dtype=float32)

In [14]:
v = keras.Variable(keras.random.normal(shape=(3,1)))
v.value

Array([[-0.32251447],
       [ 1.0465071 ],
       [-0.8690599 ]], dtype=float32)

In [17]:
v.assign(v + 1.0)

Array([[0.6774855 ],
       [2.0465071 ],
       [0.13094008]], dtype=float32)

In [18]:
keras.ops.square(v)

Array([[0.45898664],
       [4.1881914 ],
       [0.0171453 ]], dtype=float32)

In [36]:
import jax
input_const = keras.ops.convert_to_tensor([3.])
input_const.shape

def sq_tens(x):
    return keras.ops.sum(keras.ops.square(x))
g_func = jax.value_and_grad(sq_tens)
g_func(input_const)

(Array(9., dtype=float32), Array([6.], dtype=float32))

In [38]:
a = 2.0
b = 3.0
jax.grad(jax.lax.mul)(b, a)

Array(2., dtype=float32, weak_type=True)

In [41]:
def position(time):
    return 4.9 * (time ** 2.0)
d1_func = jax.grad(position)
d1 = d1_func(2.0)
d2 = jax.grad(d1_func)(d1)
d2

Array(9.8, dtype=float32)